### ISSUE TITLE
Keep getting HTTP Error 403: Forbidden after a short while of use - giphy api limits?

### ISSUE THREAD

**Issue by gavinc** [rhaining/lucille#9]
Here's the flow from the log:

```
all+better+now%3F
http://api.giphy.com/v1/gifs/search?q=all+better+now%3F&api_key=dc6zaTOxFJmzC
http://media3.giphy.com/media/10zbOqrx0oB3bO/giphy.gif
{"status": "sent"}
HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
```

(then I ctrl-c it, and tell it to sleep for a while, presumably to let the giphy rate limit expire?) 

```
stella-admin@ubuntu:~/lucille$ sleep 60 && python lucille.py
Traceback (most recent call last):
  File "lucille.py", line 42, in <module>
    for r in Room.list():
  File "build/bdist.linux-x86_64/egg/hipchat/connection.py", line 17, in newfunc
  File "build/bdist.linux-x86_64/egg/hipchat/connection.py", line 33, in call_hipchat
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

Not long enough of a pause I presume.

**Comment by scottwallacesh** [comment]
This looks like a problem connecting to Hipchat and not Giphy.

```
Traceback (most recent call last):
  File "lucille.py", line 42, in <module>
    for r in Room.list():
  File "build/bdist.linux-x86_64/egg/hipchat/connection.py", line 17, in newfunc
  File "build/bdist.linux-x86_64/egg/hipchat/connection.py", line 33, in call_hipchat
```

I'm getting the exact same thing and I see this in the Hipchat logs:
```
/var/log/hipchat/web.log:2017-08-10T13:12:59.851725+00:00 hipchat web[8580]: api_rooms/index#REQ3A337E uid-anon 10ms [info] Auth token valid: cea596a386909fb7dbc8f0bc53d6f41d
/var/log/hipchat/web.log:2017-08-10T13:12:59.851808+00:00 hipchat web[8580]: api_rooms/index#REQ3A337E uid-anon 11ms [info] RateLimiter: current usage of 'api:cea596a386909fb7dbc8f0bc53d6f41d' is 100/100 (5 mins)
```
